[build]
  command = "corepack enable && pnpm install --frozen-lockfile && pnpm build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NETLIFY = "true"
  PNPM_VERSION = "8"

[[plugins]]
  package = "@netlify/plugin-nextjs"