[build]
  command = "pnpm install && NETLIFY=true SKIP_DB_CHECK=true pnpm build:netlify"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  SKIP_DB_CHECK = "true"
  NETLIFY = "true"

[dev]
  command = "pnpm dev"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/_next/static/"
  status = 200
  force = false

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404